/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectSE;

/**
 *
 * @author Yustina Yunita
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AdmManagementMenuBar = new javax.swing.JMenu();
        AdmAccMenu = new javax.swing.JMenu();
        AdmMenuMenu = new javax.swing.JMenu();
        AdmOrderMenu = new javax.swing.JMenu();
        AdmAboutMenuBar = new javax.swing.JMenu();
        AdmAdmPage = new javax.swing.JMenu();
        AdmLogoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 48)); // NOI18N
        jLabel1.setText("Welcome Admin !");

        jLabel2.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel2.setText("good luck and may you have a good day");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel2)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        AdmManagementMenuBar.setText("Management");

        AdmAccMenu.setText("Account Management");
        AdmAccMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmAccMenuMouseClicked(evt);
            }
        });
        AdmManagementMenuBar.add(AdmAccMenu);

        AdmMenuMenu.setText("Menu Management");
        AdmMenuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmMenuMenuMouseClicked(evt);
            }
        });
        AdmManagementMenuBar.add(AdmMenuMenu);

        AdmOrderMenu.setText("Order Management");
        AdmOrderMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmOrderMenuMouseClicked(evt);
            }
        });
        AdmManagementMenuBar.add(AdmOrderMenu);

        jMenuBar1.add(AdmManagementMenuBar);

        AdmAboutMenuBar.setText("About");
        AdmAboutMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmAboutMenuBarActionPerformed(evt);
            }
        });

        AdmAdmPage.setText("Admin page");
        AdmAdmPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmAdmPageMouseClicked(evt);
            }
        });
        AdmAboutMenuBar.add(AdmAdmPage);

        AdmLogoutMenu.setText("Logout");
        AdmLogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmLogoutMenuMouseClicked(evt);
            }
        });
        AdmLogoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmLogoutMenuActionPerformed(evt);
            }
        });
        AdmAboutMenuBar.add(AdmLogoutMenu);

        jMenuBar1.add(AdmAboutMenuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdmAboutMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmAboutMenuBarActionPerformed

    }//GEN-LAST:event_AdmAboutMenuBarActionPerformed

    private void AdmLogoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmLogoutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmLogoutMenuActionPerformed

    private void AdmAccMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmAccMenuMouseClicked
        dispose();
        AdminAM AAM = new AdminAM();
        AAM.setLocationRelativeTo(null);
        AAM.setLocationRelativeTo(null);
        AAM.setVisible(true);
    }//GEN-LAST:event_AdmAccMenuMouseClicked

    private void AdmLogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmLogoutMenuMouseClicked
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_AdmLogoutMenuMouseClicked

    private void AdmAdmPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmAdmPageMouseClicked
        dispose();
        AdminPage AP = new AdminPage();
        AP.setLocationRelativeTo(null);
        AP.setLocationRelativeTo(null);
        AP.setVisible(true);
    }//GEN-LAST:event_AdmAdmPageMouseClicked

    private void AdmMenuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmMenuMenuMouseClicked
        dispose();
        AdminMM AMM = new AdminMM();
        AMM.setLocationRelativeTo(null);
        AMM.setLocationRelativeTo(null);
        AMM.setVisible(true);
    }//GEN-LAST:event_AdmMenuMenuMouseClicked

    private void AdmOrderMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmOrderMenuMouseClicked
        dispose();
        AdminOM AOM = new AdminOM();
        AOM.setLocationRelativeTo(null);
        AOM.setLocationRelativeTo(null);
        AOM.setVisible(true);
    }//GEN-LAST:event_AdmOrderMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AdmAboutMenuBar;
    private javax.swing.JMenu AdmAccMenu;
    private javax.swing.JMenu AdmAdmPage;
    private javax.swing.JMenu AdmLogoutMenu;
    private javax.swing.JMenu AdmManagementMenuBar;
    private javax.swing.JMenu AdmMenuMenu;
    private javax.swing.JMenu AdmOrderMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
