package ProjectSE;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminAM extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public AdminAM() {
        initComponents();
        Config DB = new Config();
        DB.conn();
        con = DB.con;
        stat = DB.stm;
    }
    
    public void table() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Email");
        tbl.addColumn("Username");
        tbl.addColumn("Password");

        try {
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM user");
        
            while (rs.next()) {
            tbl.addRow(new Object[] {
                rs.getString("email"),
                rs.getString("username"),
                rs.getString("password")
            }); 
            }
            UserTable.setModel(tbl);
        } catch (Exception e){
            JOptionPane.showMessageDialog (null, "Connection Error" + e.getMessage());
        }
    }
    
    void delete() {
    AccEmailTextField.setText("");
    AccUnameTextField.setText("");
    AccPassTextField.setText(""); 
    }
    
    void find(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Email");
        tbl.addColumn("Username");
        tbl.addColumn("Password");
        
         try {
            String FindQuery = "SELECT * FROM user WHERE username like '%" + AccFindTextField.getText() + "%'";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(FindQuery);
            
            while (rs.next()) {
                tbl.addRow(new Object[] {
                rs.getString("email"),
                rs.getString("username"),
                rs.getString("password")
            });       
            UserTable.setModel(tbl);
            } 
        }catch (Exception e) {
        }  
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AccEmailLabel = new javax.swing.JLabel();
        AccUnameLabel = new javax.swing.JLabel();
        AccPassLabel = new javax.swing.JLabel();
        AccAddButton = new javax.swing.JButton();
        AccEmailTextField = new javax.swing.JTextField();
        AccUnameTextField = new javax.swing.JTextField();
        AccUpdateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        AccFindButton = new javax.swing.JButton();
        AccShowButton = new javax.swing.JButton();
        AccDeleteButton = new javax.swing.JButton();
        AccFindTextField = new javax.swing.JTextField();
        AccPassTextField = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AccAccMenu = new javax.swing.JMenu();
        AccMenuMenu = new javax.swing.JMenu();
        AccOrderMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        AccAdmPage = new javax.swing.JMenu();
        AccLogoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        AccEmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccEmailLabel.setText("Email");

        AccUnameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccUnameLabel.setText("Username");

        AccPassLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccPassLabel.setText("Password");

        AccAddButton.setBackground(new java.awt.Color(204, 204, 255));
        AccAddButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccAddButton.setText("Add");
        AccAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccAddButtonMouseClicked(evt);
            }
        });
        AccAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccAddButtonActionPerformed(evt);
            }
        });

        AccEmailTextField.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        AccUnameTextField.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        AccUpdateButton.setBackground(new java.awt.Color(204, 204, 255));
        AccUpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccUpdateButton.setText("Update");
        AccUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccUpdateButtonMouseClicked(evt);
            }
        });
        AccUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccUpdateButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel6.setText("Account Management Center");

        UserTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Email", "Username", "Password"
            }
        ));
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);

        AccFindButton.setBackground(new java.awt.Color(204, 204, 255));
        AccFindButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccFindButton.setText("Find");
        AccFindButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccFindButtonMouseClicked(evt);
            }
        });
        AccFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccFindButtonActionPerformed(evt);
            }
        });

        AccShowButton.setBackground(new java.awt.Color(204, 204, 255));
        AccShowButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccShowButton.setText("Show");
        AccShowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccShowButtonMouseClicked(evt);
            }
        });
        AccShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccShowButtonActionPerformed(evt);
            }
        });

        AccDeleteButton.setBackground(new java.awt.Color(204, 204, 255));
        AccDeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AccDeleteButton.setText("Delete");
        AccDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccDeleteButtonMouseClicked(evt);
            }
        });

        AccFindTextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AccFindTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccFindTextFieldActionPerformed(evt);
            }
        });

        AccPassTextField.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        AccPassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccPassTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(AccPassLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AccPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(AccEmailLabel)
                                    .addGap(71, 71, 71)
                                    .addComponent(AccEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(AccUnameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AccUnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AccAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AccShowButton)
                                .addGap(18, 18, 18)
                                .addComponent(AccUpdateButton)
                                .addGap(18, 18, 18)
                                .addComponent(AccDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AccFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AccFindTextField))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccFindButton)
                            .addComponent(AccFindTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccEmailLabel)
                            .addComponent(AccEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccUnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccUnameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccPassLabel)
                            .addComponent(AccPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccAddButton)
                            .addComponent(AccShowButton)
                            .addComponent(AccUpdateButton)
                            .addComponent(AccDeleteButton))
                        .addGap(47, 47, 47)))
                .addGap(0, 100, Short.MAX_VALUE))
        );

        jMenu1.setText("Management");

        AccAccMenu.setText("Account Management");
        AccAccMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccAccMenuMouseClicked(evt);
            }
        });
        jMenu1.add(AccAccMenu);

        AccMenuMenu.setText("Menu Management");
        AccMenuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccMenuMenuMouseClicked(evt);
            }
        });
        jMenu1.add(AccMenuMenu);

        AccOrderMenu.setText("Order Management");
        AccOrderMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccOrderMenuMouseClicked(evt);
            }
        });
        jMenu1.add(AccOrderMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        AccAdmPage.setText("Back to Admin Page");
        AccAdmPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccAdmPageMouseClicked(evt);
            }
        });
        jMenu2.add(AccAdmPage);

        AccLogoutMenu.setText("Logout");
        AccLogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccLogoutMenuMouseClicked(evt);
            }
        });
        jMenu2.add(AccLogoutMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccAddButtonActionPerformed

    }//GEN-LAST:event_AccAddButtonActionPerformed

    private void AccUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccUpdateButtonActionPerformed

    }//GEN-LAST:event_AccUpdateButtonActionPerformed

    private void AccShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccShowButtonActionPerformed

    }//GEN-LAST:event_AccShowButtonActionPerformed

    private void AccFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccFindButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccFindButtonActionPerformed

    private void AccPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccPassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccPassTextFieldActionPerformed

    private void AccAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccAddButtonMouseClicked
        String email = AccEmailTextField.getText();
        String username = AccUnameTextField.getText();
        String password = new String(AccPassTextField.getPassword());  
        
        try {
            if (email.isEmpty() || username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all fields");
            } else {
                // Check if email already exists
                String selectEmailQuery = "SELECT * FROM user WHERE email='" + email + "'";
                ResultSet emailResultSet = stat.executeQuery(selectEmailQuery);
                if (emailResultSet.next()) {
                    JOptionPane.showMessageDialog(null, "Email already exists! Please use another email");
                } else {
                    // Check if username already exists
                    String selectUserQuery = "SELECT * FROM user WHERE username='" + username + "'";
                    ResultSet userResultSet = stat.executeQuery(selectUserQuery);
                    if (userResultSet.next()) {
                        JOptionPane.showMessageDialog(null, "Username already exists! Please choose another username");
                    } else {
                        // Insert new user into database
                        String insertQuery = "INSERT INTO user (email, username, password) VALUES ('" + email + "', '" + username + "', '" + password + "')";
                        int result = stat.executeUpdate(insertQuery);
                        if (result == 1) {
                            JOptionPane.showMessageDialog(null, "Successfully Add a New User");
                            AccEmailTextField.setText("");
                            AccUnameTextField.setText("");
                            AccPassTextField.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Failed Add New User! Please Try Again!!");
                        }
                    }
                }
            }
        } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, " Error! Please Try Again!!");
        }
    }//GEN-LAST:event_AccAddButtonMouseClicked

    private void AccShowButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccShowButtonMouseClicked
        try {
            String showQuery = "SELECT * FROM user WHERE email ='" + AccEmailTextField.getText() + "'";
            ResultSet rs = stat.executeQuery(showQuery);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Showing User Data");
        }
        table();
        delete();
    }//GEN-LAST:event_AccShowButtonMouseClicked

    private void AccUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccUpdateButtonMouseClicked
 try {
            String UpdateQuery = "UPDATE user SET email='" + AccEmailTextField.getText()
                    + "', username='" + AccUnameTextField.getText()
                    + "', password='" + AccPassTextField.getText()
                    + "', email='" + AccEmailTextField.getText()
                    + "' WHERE email ='" + AccEmailTextField.getText() + "'";
            
            PreparedStatement pst = con.prepareStatement(UpdateQuery);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated the User Data!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to Update the User Data! Please Try Again!!");
}
    }//GEN-LAST:event_AccUpdateButtonMouseClicked

    private void AccDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccDeleteButtonMouseClicked
    try {
            String DeleteQuery = "DELETE FROM user WHERE email ='" + AccEmailTextField.getText() + "'";
            PreparedStatement pst = con.prepareStatement(DeleteQuery);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Delete User Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error! Failed Delete User Data");
        }       
    }//GEN-LAST:event_AccDeleteButtonMouseClicked

    private void AccFindButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccFindButtonMouseClicked
        find();
    }//GEN-LAST:event_AccFindButtonMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void AccLogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccLogoutMenuMouseClicked
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_AccLogoutMenuMouseClicked

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
    int row = UserTable.rowAtPoint(evt.getPoint());

    String email = UserTable.getValueAt(row, 0).toString();
    AccEmailTextField.setText(email);

    String username = UserTable.getValueAt(row, 1).toString();
    AccUnameTextField.setText(username);

    String password = UserTable.getValueAt(row, 2).toString();
    AccPassTextField.setText(password);

    }//GEN-LAST:event_UserTableMouseClicked

    private void AccAdmPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccAdmPageMouseClicked
        dispose();
        AdminPage AP = new AdminPage();
        AP.setLocationRelativeTo(null);
        AP.setLocationRelativeTo(null);
        AP.setVisible(true);
    }//GEN-LAST:event_AccAdmPageMouseClicked

    private void AccFindTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccFindTextFieldActionPerformed
    
    }//GEN-LAST:event_AccFindTextFieldActionPerformed

    private void AccMenuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccMenuMenuMouseClicked
        dispose();
        AdminMM AMM = new AdminMM();
        AMM.setLocationRelativeTo(null);
        AMM.setLocationRelativeTo(null);
        AMM.setVisible(true);
    }//GEN-LAST:event_AccMenuMenuMouseClicked

    private void AccAccMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccAccMenuMouseClicked
        dispose();
        AdminAM AAM = new AdminAM();
        AAM.setLocationRelativeTo(null);
        AAM.setLocationRelativeTo(null);
        AAM.setVisible(true);
    }//GEN-LAST:event_AccAccMenuMouseClicked

    private void AccOrderMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccOrderMenuMouseClicked
        dispose();
        AdminOM AOM = new AdminOM();
        AOM.setLocationRelativeTo(null);
        AOM.setLocationRelativeTo(null);
        AOM.setVisible(true);
    }//GEN-LAST:event_AccOrderMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AccAccMenu;
    private javax.swing.JButton AccAddButton;
    private javax.swing.JMenu AccAdmPage;
    private javax.swing.JButton AccDeleteButton;
    private javax.swing.JLabel AccEmailLabel;
    private javax.swing.JTextField AccEmailTextField;
    private javax.swing.JButton AccFindButton;
    private javax.swing.JTextField AccFindTextField;
    private javax.swing.JMenu AccLogoutMenu;
    private javax.swing.JMenu AccMenuMenu;
    private javax.swing.JMenu AccOrderMenu;
    private javax.swing.JLabel AccPassLabel;
    private javax.swing.JPasswordField AccPassTextField;
    private javax.swing.JButton AccShowButton;
    private javax.swing.JLabel AccUnameLabel;
    private javax.swing.JTextField AccUnameTextField;
    private javax.swing.JButton AccUpdateButton;
    private javax.swing.JTable UserTable;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
