/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectSE;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;


/**
 *
 * @author Yustina Yunita
 */
public class AdminOM extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public AdminOM() {
        initComponents();
        Config DB = new Config();
        DB.conn();
        con = DB.con;
        stat = DB.stm;
    }

    public void table() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Order ID");
        tbl.addColumn("Receiver Name");
        tbl.addColumn("Address");
        tbl.addColumn("Phone Number");
        tbl.addColumn("Note");
        tbl.addColumn("Payment Method");
        tbl.addColumn("Menu Name");
        tbl.addColumn("Quantity");
        tbl.addColumn("Price");
        tbl.addColumn("Total");
        tbl.addColumn("Delivery Status");

        try {
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM orders");
        
            while (rs.next()) {
            tbl.addRow(new Object[] {
                rs.getString("order_id"),
                rs.getString("name"),
                rs.getString("address"),
                rs.getString("phone_number"),
                rs.getString("note"),
                rs.getString("payment_method"),
                rs.getString("menu_name"),
                rs.getString("quantity"),
                rs.getString("price"),
                rs.getString("total"),
                rs.getString("delivery_status")
                }); 
            }
            OrderTable.setModel(tbl);
        } catch (Exception e){
            JOptionPane.showMessageDialog (null, "Connection Error" + e.getMessage());
        }
    }
    
    void delete() {
        OMIDTF.setText("");
        OMNameTF.setText("");
        OMAddressTF.setText(""); 
        OMPhoneTF.setText("");
        OMNoteTF.setText("");
        OMPaymentTF.setText(""); 
        OMMenuNameTF.setText("");
        OMQuantityTF.setText("");
        OMPriceTF.setText(""); 
        OMTotalTF.setText("");
        OMDeliveryTF.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        OMIDTF = new javax.swing.JTextField();
        OMNameTF = new javax.swing.JTextField();
        OMAddressTF = new javax.swing.JTextField();
        OMPhoneTF = new javax.swing.JTextField();
        OMNoteTF = new javax.swing.JTextField();
        OMPaymentTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        OMMenuNameTF = new javax.swing.JTextField();
        OMQuantityTF = new javax.swing.JTextField();
        OMPriceTF = new javax.swing.JTextField();
        OMTotalTF = new javax.swing.JTextField();
        OMDeliveryTF = new javax.swing.JTextField();
        OMAddBtn = new javax.swing.JButton();
        OMShowBtn = new javax.swing.JButton();
        OMEditBtn = new javax.swing.JButton();
        OMDeleteBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AOMAccMenu = new javax.swing.JMenu();
        AOMMenuMenu = new javax.swing.JMenu();
        AOMOrderMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        AOMBackMenu = new javax.swing.JMenu();
        AOMLogoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        jLabel1.setText("Order Management");

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Name", "Address", "Phone Number", "Note", "Payment Method", "Menu Name", "Quantity", "Price", "Total", "Delivery Status"
            }
        ));
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(OrderTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Order ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Receiver Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Note");

        OMIDTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMNameTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OMNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OMNameTFActionPerformed(evt);
            }
        });

        OMAddressTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMPhoneTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMNoteTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMPaymentTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Payment Method");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Menu Name");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Price");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Total");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Delivery Status");

        OMMenuNameTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMQuantityTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMPriceTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMTotalTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OMDeliveryTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OMDeliveryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OMDeliveryTFActionPerformed(evt);
            }
        });

        OMAddBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OMAddBtn.setText("Add");
        OMAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMAddBtnMouseClicked(evt);
            }
        });
        OMAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OMAddBtnActionPerformed(evt);
            }
        });

        OMShowBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OMShowBtn.setText("Show");
        OMShowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMShowBtnMouseClicked(evt);
            }
        });

        OMEditBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OMEditBtn.setText("Edit");
        OMEditBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMEditBtnMouseClicked(evt);
            }
        });

        OMDeleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        OMDeleteBtn.setText("Delete");
        OMDeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OMDeleteBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OMPaymentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OMNoteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OMPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OMAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OMNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OMIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(OMMenuNameTF)
                                    .addComponent(OMQuantityTF)
                                    .addComponent(OMPriceTF)
                                    .addComponent(OMTotalTF)
                                    .addComponent(OMDeliveryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(OMAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OMShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OMEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OMDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(OMMenuNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(OMQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(OMPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(OMTotalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(OMDeliveryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OMAddBtn)
                            .addComponent(OMShowBtn)
                            .addComponent(OMEditBtn)
                            .addComponent(OMDeleteBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(OMIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(OMNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(OMAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(OMPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OMNoteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OMPaymentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jMenu1.setText("Management");

        AOMAccMenu.setText("Account Management");
        AOMAccMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AOMAccMenuMouseClicked(evt);
            }
        });
        jMenu1.add(AOMAccMenu);

        AOMMenuMenu.setText("Menu Management");
        AOMMenuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AOMMenuMenuMouseClicked(evt);
            }
        });
        jMenu1.add(AOMMenuMenu);

        AOMOrderMenu.setText("Order Management");
        AOMOrderMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AOMOrderMenuMouseClicked(evt);
            }
        });
        jMenu1.add(AOMOrderMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        AOMBackMenu.setText("Back to Admin Page");
        AOMBackMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AOMBackMenuMouseClicked(evt);
            }
        });
        jMenu2.add(AOMBackMenu);

        AOMLogoutMenu.setText("Logout");
        AOMLogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AOMLogoutMenuMouseClicked(evt);
            }
        });
        jMenu2.add(AOMLogoutMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AOMBackMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOMBackMenuMouseClicked
        dispose();
        AdminPage AP = new AdminPage();
        AP.setLocationRelativeTo(null);
        AP.setLocationRelativeTo(null);
        AP.setVisible(true);
    }//GEN-LAST:event_AOMBackMenuMouseClicked

    private void AOMMenuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOMMenuMenuMouseClicked
        dispose();
        AdminMM AMM = new AdminMM();
        AMM.setLocationRelativeTo(null);
        AMM.setLocationRelativeTo(null);
        AMM.setVisible(true);
    }//GEN-LAST:event_AOMMenuMenuMouseClicked

    private void AOMAccMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOMAccMenuMouseClicked
        dispose();
        AdminAM AAM = new AdminAM();
        AAM.setLocationRelativeTo(null);
        AAM.setLocationRelativeTo(null);
        AAM.setVisible(true);
    }//GEN-LAST:event_AOMAccMenuMouseClicked

    private void AOMOrderMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOMOrderMenuMouseClicked
        dispose();
        AdminOM AOM = new AdminOM();
        AOM.setLocationRelativeTo(null);
        AOM.setLocationRelativeTo(null);
        AOM.setVisible(true);
    }//GEN-LAST:event_AOMOrderMenuMouseClicked

    private void AOMLogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AOMLogoutMenuMouseClicked
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_AOMLogoutMenuMouseClicked

    private void OMNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OMNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OMNameTFActionPerformed

    private void OMDeliveryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OMDeliveryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OMDeliveryTFActionPerformed

    private void OMAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OMAddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OMAddBtnActionPerformed

    private void OMAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMAddBtnMouseClicked
        String OrderID = OMIDTF.getText();
        String Name = OMNameTF.getText();
        String Address = OMAddressTF.getText();
        String Phone = OMPhoneTF.getText();
        String Note = OMNoteTF.getText();
        String Payment = OMPaymentTF.getText();
        String MenuName = OMMenuNameTF.getText();
        int Quantity = Integer.parseInt(OMQuantityTF.getText());
        double Price = Double.parseDouble(OMPriceTF.getText());
        double Total = Double.parseDouble(OMTotalTF.getText());
        String DeliverStat = OMDeliveryTF.getText();

        try {
            if (OrderID.isEmpty() || Name.isEmpty() || Address.isEmpty() || Phone.isEmpty() || Note.isEmpty() || Payment.isEmpty() || MenuName.isEmpty() || Quantity <= 0 || Price <= 0 || Total <= 0 || DeliverStat.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all fields and ensure numerical values are valid");
            } else {
                String insertOrderQuery = "INSERT INTO orders (name, address, phone_number, note, payment_method, menu_name, quantity, price, total) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement insertOrderStatement = con.prepareStatement(insertOrderQuery);
                insertOrderStatement.setString(1, Name);
                insertOrderStatement.setString(2, Address);
                insertOrderStatement.setString(3, Phone);
                insertOrderStatement.setString(4, Note);
                insertOrderStatement.setString(5, Payment);
                insertOrderStatement.setString(6, MenuName);
                insertOrderStatement.setInt(7, Quantity);
                insertOrderStatement.setDouble(8, Price);
                insertOrderStatement.setDouble(9, Total);
                insertOrderStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Order successfully inserted!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid numerical input. Please enter valid numbers for quantity, price, and total.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error inserting order. Please try again!");
        }
    }//GEN-LAST:event_OMAddBtnMouseClicked

    private void OMShowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMShowBtnMouseClicked
        try {
                String showQuery = "SELECT * FROM orders WHERE order_id ='" + OMIDTF.getText() + "'";
                ResultSet rs = stat.executeQuery(showQuery);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Showing Order");
            }
        table();
        delete();
    }//GEN-LAST:event_OMShowBtnMouseClicked

    private void OMEditBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMEditBtnMouseClicked
    String OrderID = OMIDTF.getText();
    String Name = OMNameTF.getText();
    String Address = OMAddressTF.getText();
    String Phone = OMPhoneTF.getText();
    String Note = OMNoteTF.getText();
    String Payment = OMPaymentTF.getText();
    String MenuName = OMMenuNameTF.getText();
    int Quantity = Integer.parseInt(OMQuantityTF.getText());
    double Price = Double.parseDouble(OMPriceTF.getText());
    double Total = Double.parseDouble(OMTotalTF.getText());
    String DeliverStat = OMDeliveryTF.getText();

    try {
        String updateQuery = "UPDATE orders SET name=?, address=?, phone_number=?, note=?, payment_method=?, menu_name=?, quantity=?, price=?, total=?, delivery_status=? WHERE order_id=?";
        PreparedStatement updateStatement = con.prepareStatement(updateQuery);
        updateStatement.setString(1, Name);
        updateStatement.setString(2, Address);
        updateStatement.setString(3, Phone);
        updateStatement.setString(4, Note);
        updateStatement.setString(5, Payment);
        updateStatement.setString(6, MenuName);
        updateStatement.setInt(7, Quantity);
        updateStatement.setDouble(8, Price);
        updateStatement.setDouble(9, Total);
        updateStatement.setString(10, DeliverStat);
        updateStatement.setString(11, OrderID);
        updateStatement.executeUpdate();
        JOptionPane.showMessageDialog(null, "Order updated successfully!");
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Invalid numerical input. Please enter valid numbers for quantity, price, and total.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error updating order. Please try again!");
    }
    }//GEN-LAST:event_OMEditBtnMouseClicked

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked
    int selectedRow = OrderTable.getSelectedRow();
    if (selectedRow != -1) {
        OMIDTF.setText(OrderTable.getValueAt(selectedRow, 0).toString());
        OMNameTF.setText(OrderTable.getValueAt(selectedRow, 1).toString());
        OMAddressTF.setText(OrderTable.getValueAt(selectedRow, 2).toString());
        OMPhoneTF.setText(OrderTable.getValueAt(selectedRow, 3).toString());
        OMNoteTF.setText(OrderTable.getValueAt(selectedRow, 4).toString());
        OMPaymentTF.setText(OrderTable.getValueAt(selectedRow, 5).toString());
        OMMenuNameTF.setText(OrderTable.getValueAt(selectedRow, 6).toString());
        OMQuantityTF.setText(OrderTable.getValueAt(selectedRow, 7).toString());
        OMPriceTF.setText(OrderTable.getValueAt(selectedRow, 8).toString());
        OMTotalTF.setText(OrderTable.getValueAt(selectedRow, 9).toString());
        OMDeliveryTF.setText(OrderTable.getValueAt(selectedRow, 10).toString());
        
        OMIDTF.setEditable(false);
        OMNameTF.setEditable(false);
        OMAddressTF.setEditable(false);
        OMPhoneTF.setEditable(false);
        OMNoteTF.setEditable(false);
        OMPaymentTF.setEditable(false);
        OMMenuNameTF.setEditable(false);
        OMQuantityTF.setEditable(false);
        OMPriceTF.setEditable(false);
        OMTotalTF.setEditable(false);
        OMDeliveryTF.setEditable(true);
    }
    }//GEN-LAST:event_OrderTableMouseClicked

    private void OMDeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OMDeleteBtnMouseClicked
    try {
            String DeleteQuery = "DELETE FROM orders WHERE order_id ='" + OMIDTF.getText() + "'";
            PreparedStatement pst = con.prepareStatement(DeleteQuery);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Delete Order Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error! Failed Delete Order Data");
        }       
    }//GEN-LAST:event_OMDeleteBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AOMAccMenu;
    private javax.swing.JMenu AOMBackMenu;
    private javax.swing.JMenu AOMLogoutMenu;
    private javax.swing.JMenu AOMMenuMenu;
    private javax.swing.JMenu AOMOrderMenu;
    private javax.swing.JButton OMAddBtn;
    private javax.swing.JTextField OMAddressTF;
    private javax.swing.JButton OMDeleteBtn;
    private javax.swing.JTextField OMDeliveryTF;
    private javax.swing.JButton OMEditBtn;
    private javax.swing.JTextField OMIDTF;
    private javax.swing.JTextField OMMenuNameTF;
    private javax.swing.JTextField OMNameTF;
    private javax.swing.JTextField OMNoteTF;
    private javax.swing.JTextField OMPaymentTF;
    private javax.swing.JTextField OMPhoneTF;
    private javax.swing.JTextField OMPriceTF;
    private javax.swing.JTextField OMQuantityTF;
    private javax.swing.JButton OMShowBtn;
    private javax.swing.JTextField OMTotalTF;
    private javax.swing.JTable OrderTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
