/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectSE;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Yustina Yunita
 */
public class LoginPage extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
            
    public LoginPage() {
        initComponents();
        Config DB = new Config();
        DB.conn();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LogPageLabel = new javax.swing.JLabel();
        LogLoginButton = new javax.swing.JButton();
        LogRegisterButton = new javax.swing.JButton();
        LogPageIntroLabel = new javax.swing.JLabel();
        LogUnameLabel = new javax.swing.JLabel();
        LogUnameTextField = new javax.swing.JTextField();
        LogPassLabel = new javax.swing.JLabel();
        LogPassTextField = new javax.swing.JPasswordField();
        LogBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectSE/aa.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        LogPageLabel.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        LogPageLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogPageLabel.setText("Login Page");

        LogLoginButton.setBackground(new java.awt.Color(255, 153, 153));
        LogLoginButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LogLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LogLoginButton.setText("Login");
        LogLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogLoginButtonActionPerformed(evt);
            }
        });

        LogRegisterButton.setBackground(new java.awt.Color(255, 153, 153));
        LogRegisterButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LogRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        LogRegisterButton.setText("Register");
        LogRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogRegisterButtonActionPerformed(evt);
            }
        });

        LogPageIntroLabel.setFont(new java.awt.Font("Gungsuh", 2, 12)); // NOI18N
        LogPageIntroLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogPageIntroLabel.setText("Welcome customer~! Please Login");

        LogUnameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LogUnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogUnameLabel.setText("Username :");

        LogUnameTextField.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        LogUnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogUnameTextFieldActionPerformed(evt);
            }
        });

        LogPassLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LogPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogPassLabel.setText("Password:");

        LogBackButton.setBackground(new java.awt.Color(255, 153, 153));
        LogBackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LogBackButton.setForeground(new java.awt.Color(255, 255, 255));
        LogBackButton.setText("Back");
        LogBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LogUnameLabel)
                                .addComponent(LogPassLabel))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LogPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LogUnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LogLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(LogBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogRegisterButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogPageIntroLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(LogPageLabel)))
                        .addGap(37, 37, 37)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(LogPageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogPageIntroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogUnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogUnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogPassLabel)
                    .addComponent(LogPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogLoginButton)
                    .addComponent(LogBackButton)
                    .addComponent(LogRegisterButton))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogUnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogUnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogUnameTextFieldActionPerformed

    private void LogRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogRegisterButtonActionPerformed
        dispose();
        RegisterPage rp = new RegisterPage();
        rp.setLocationRelativeTo(null);
        rp.setVisible(true);
    }//GEN-LAST:event_LogRegisterButtonActionPerformed

    private void LogLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogLoginButtonActionPerformed
       try {
        String username = LogUnameTextField.getText();
        String password = LogPassTextField.getText();

        String sql = "SELECT * FROM user WHERE username='" + username + "' AND password='" + password + "'";
        ResultSet rs = stat.executeQuery(sql);

        if (rs.next()) {
            String dbUsername = rs.getString("username");
            String dbPassword = rs.getString("password");

            if (username.equals(dbUsername) && password.equals(dbPassword)) {
                if (username.equals("admin") && password.equals("admin123")) {
                    JOptionPane.showMessageDialog(null, "Welcome admin");
                    AdminPage AP = new AdminPage();
                    AP.setLocationRelativeTo(null);
                    AP.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Welcome " + username);
                    UserPage UP = new UserPage();
                    UP.setLocationRelativeTo(null);
                    UP.setVisible(true);
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or password");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect username or password");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Login Error! Please Try Again!!");
    }

    }//GEN-LAST:event_LogLoginButtonActionPerformed

    private void LogBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBackButtonActionPerformed
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_LogBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JButton LogBackButton;
    private javax.swing.JButton LogLoginButton;
    private javax.swing.JLabel LogPageIntroLabel;
    private javax.swing.JLabel LogPageLabel;
    private javax.swing.JLabel LogPassLabel;
    private javax.swing.JPasswordField LogPassTextField;
    private javax.swing.JButton LogRegisterButton;
    private javax.swing.JLabel LogUnameLabel;
    private javax.swing.JTextField LogUnameTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
