package ProjectSE;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yustina Yunita
 */
public class RegisterPage extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public RegisterPage() {
        initComponents();
        Config DB = new Config();
        DB.conn();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagelabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RegPageLabel = new javax.swing.JLabel();
        RegEmailTextField = new javax.swing.JTextField();
        RegUnameTextField = new javax.swing.JTextField();
        RegLoginButton = new javax.swing.JButton();
        RegRegisterButon = new javax.swing.JButton();
        RegPageIntroLabel = new javax.swing.JLabel();
        RegPassTextField = new javax.swing.JPasswordField();
        RegEmailLabel = new javax.swing.JLabel();
        RegUnameLabel = new javax.swing.JLabel();
        RegPassLabel = new javax.swing.JLabel();
        RegBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectSE/aa.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        RegPageLabel.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        RegPageLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegPageLabel.setText("Register Page");

        RegEmailTextField.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        RegUnameTextField.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        RegUnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegUnameTextFieldActionPerformed(evt);
            }
        });

        RegLoginButton.setBackground(new java.awt.Color(255, 153, 153));
        RegLoginButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        RegLoginButton.setText("Login");
        RegLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegLoginButtonActionPerformed(evt);
            }
        });

        RegRegisterButon.setBackground(new java.awt.Color(255, 153, 153));
        RegRegisterButon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegRegisterButon.setForeground(new java.awt.Color(255, 255, 255));
        RegRegisterButon.setText("Register");
        RegRegisterButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegRegisterButonActionPerformed(evt);
            }
        });

        RegPageIntroLabel.setFont(new java.awt.Font("Gungsuh", 2, 12)); // NOI18N
        RegPageIntroLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegPageIntroLabel.setText("Please fill in the form to register yourself!");

        RegEmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegEmailLabel.setText("Email :");

        RegUnameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegUnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegUnameLabel.setText("Username :");

        RegPassLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegPassLabel.setForeground(new java.awt.Color(255, 255, 255));
        RegPassLabel.setText("Password:");

        RegBackButton.setBackground(new java.awt.Color(255, 153, 153));
        RegBackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegBackButton.setForeground(new java.awt.Color(255, 255, 255));
        RegBackButton.setText("Back");
        RegBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(RegBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(RegRegisterButon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegEmailLabel)
                            .addComponent(RegUnameLabel)
                            .addComponent(RegPassLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegUnameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegEmailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegPassTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegPageIntroLabel)
                        .addGap(27, 27, 27)))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegPageLabel)
                .addGap(161, 161, 161))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(RegPageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegPageIntroLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegEmailLabel)
                    .addComponent(RegEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegUnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegUnameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegPassLabel)
                    .addComponent(RegPassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegLoginButton)
                    .addComponent(RegRegisterButon)
                    .addComponent(RegBackButton))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegUnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegUnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegUnameTextFieldActionPerformed

    private void RegLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegLoginButtonActionPerformed
        dispose();
        LoginPage lp = new LoginPage();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
    }//GEN-LAST:event_RegLoginButtonActionPerformed

    private void RegBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegBackButtonActionPerformed
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_RegBackButtonActionPerformed

    private void RegRegisterButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegRegisterButonActionPerformed
        String email = RegEmailTextField.getText();
        String username = RegUnameTextField.getText();
        String password = new String(RegPassTextField.getPassword());
        
        try {
            if (email.isEmpty() || username.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all fields");
            } else {
                // Check if email already exists
                String selectEmailQuery = "SELECT * FROM user WHERE email='" + email + "'";
                ResultSet emailResultSet = stat.executeQuery(selectEmailQuery);
                if (emailResultSet.next()) {
                    JOptionPane.showMessageDialog(null, "Email already exists! Please use another email");
                } else {
                    String selectUserQuery = "SELECT * FROM user WHERE username='" + username + "'";
                    ResultSet userResultSet = stat.executeQuery(selectUserQuery);
                    if (userResultSet.next()) {
                        JOptionPane.showMessageDialog(null, "Username already exists! Please choose another username");
                    } else {
                        String insertQuery = "INSERT INTO user (email, username, password) VALUES ('" + email + "', '"+ username + "', '" + password + "')";
                        int result = stat.executeUpdate(insertQuery);
                        if (result == 1) {
                            JOptionPane.showMessageDialog(null, "Register Complete! Please Login to your account~!");
                            RegEmailTextField.setText("");
                            RegUnameTextField.setText("");
                            RegPassTextField.setText("");
                        } else {
                            JOptionPane.showMessageDialog(null, "Register Error! Please Try Again!!");
                        }
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Register Error! Please Try Again!!");
        }

    }//GEN-LAST:event_RegRegisterButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegBackButton;
    private javax.swing.JLabel RegEmailLabel;
    private javax.swing.JTextField RegEmailTextField;
    private javax.swing.JButton RegLoginButton;
    private javax.swing.JLabel RegPageIntroLabel;
    private javax.swing.JLabel RegPageLabel;
    private javax.swing.JLabel RegPassLabel;
    private javax.swing.JPasswordField RegPassTextField;
    private javax.swing.JButton RegRegisterButon;
    private javax.swing.JLabel RegUnameLabel;
    private javax.swing.JTextField RegUnameTextField;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
