/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectSE;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Yustina Yunita
 */
public class UserOP extends javax.swing.JFrame {
   Connection con;
    Statement stat;
    ResultSet rs;
    String sql; 
    DefaultComboBoxModel<String> menuModel;
    DefaultTableModel orderTableModel;

    
    public UserOP() {
        initComponents();
        Config DB = new Config();
        DB.conn();
        con = DB.con;
        stat = DB.stm;
        populateMenuComboBox();
        orderTableModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID", "Menu", "Quantity", "Price", "Total"}
        );
        OrderTable.setModel(orderTableModel);
        
    }
     private void populateMenuComboBox() {
        try {
            String sql = "SELECT menu_name FROM menu";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            menuModel = new DefaultComboBoxModel<>();
            while (rs.next()) {
                menuModel.addElement(rs.getString("menu_name"));
            }
            UOPMenuCombobox.setModel(menuModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error populating menu names: " + e.getMessage());
        }
    }
    
    private double getPriceForMenu(String menuName) {
        try {
            String sql = "SELECT price FROM menu WHERE menu_name=?";
            PreparedStatement statement = con.prepareStatement(sql);
            statement.setString(1, menuName);
            ResultSet rs = statement.executeQuery();
            if (rs.next()) {
                return rs.getDouble("price");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error getting price for menu: " + e.getMessage());
        }
        return 0.0;
    }
    
    private void calculateTotalPrice() {
        double totalPrice = 0.0;
        for (int i = 0; i < OrderTable.getRowCount(); i++) {
            Object value = OrderTable.getValueAt(i, 4);
            if (value != null) {
                double totalForRow = (double) value; // Assuming the total is in the 4th column
                totalPrice += totalForRow;
            }
        }
        jLabel3.setText(String.format("%.2f", totalPrice)); // Update the label with the total price
    }
    
    private int orderIDCounter = 1;
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UOPMenuLabel = new javax.swing.JLabel();
        UOPQuantityLabel = new javax.swing.JLabel();
        UOPMenuCombobox = new javax.swing.JComboBox<>();
        UOPQuantityCombobox = new javax.swing.JComboBox<>();
        UOPAddButton = new javax.swing.JButton();
        UOPEditButton = new javax.swing.JButton();
        UOPDeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UOPNoteTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        UOPOrderBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CashRB = new javax.swing.JRadioButton();
        TFRB = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        OPNameTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        OPAddressTF = new javax.swing.JTextField();
        OPPhoneTF = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UOPMenuMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        UOPPOMenu = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        UOPMPMenu = new javax.swing.JMenu();
        UOPCUMenu = new javax.swing.JMenu();
        UOPLogoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        UOPMenuLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPMenuLabel.setText("Menu :");

        UOPQuantityLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPQuantityLabel.setText("Quantity :");

        UOPMenuCombobox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPMenuCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UOPMenuCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UOPMenuComboboxActionPerformed(evt);
            }
        });

        UOPQuantityCombobox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPQuantityCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        UOPAddButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPAddButton.setText("Add");
        UOPAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPAddButtonMouseClicked(evt);
            }
        });
        UOPAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UOPAddButtonActionPerformed(evt);
            }
        });

        UOPEditButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPEditButton.setText("Edit");
        UOPEditButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPEditButtonMouseClicked(evt);
            }
        });
        UOPEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UOPEditButtonActionPerformed(evt);
            }
        });

        UOPDeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPDeleteButton.setText("Delete");
        UOPDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPDeleteButtonMouseClicked(evt);
            }
        });
        UOPDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UOPDeleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        jLabel1.setText("Order Page");

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Menu", "Quantity", "Price", "Total"
            }
        ));
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(OrderTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("The Total Price : Rp.");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Notes:");

        UOPNoteTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPNoteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UOPNoteTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Address:");

        UOPOrderBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UOPOrderBtn.setText("Order");
        UOPOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPOrderBtnMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Payment Method");

        CashRB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CashRB.setText("Cash");
        CashRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashRBActionPerformed(evt);
            }
        });

        TFRB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TFRB.setText("Transfer");
        TFRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Receiver Name");

        OPNameTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Phone Number");

        OPAddressTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        OPPhoneTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UOPNoteTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UOPQuantityLabel)
                                .addComponent(UOPMenuLabel)
                                .addComponent(UOPAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(OPPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(UOPEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UOPDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(UOPMenuCombobox, 0, 228, Short.MAX_VALUE)
                                    .addComponent(UOPQuantityCombobox, 0, 228, Short.MAX_VALUE)
                                    .addComponent(OPNameTF))
                                .addComponent(OPAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UOPOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(CashRB)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TFRB)))))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UOPMenuLabel)
                            .addComponent(UOPMenuCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UOPQuantityLabel)
                            .addComponent(UOPQuantityCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UOPDeleteButton)
                            .addComponent(UOPAddButton)
                            .addComponent(UOPEditButton))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(OPNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(OPPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(OPAddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(UOPNoteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CashRB)
                            .addComponent(TFRB))
                        .addGap(18, 18, 18)
                        .addComponent(UOPOrderBtn)
                        .addGap(55, 55, 55))))
        );

        jMenu1.setText("Menu");

        UOPMenuMenu.setText("Menu List");
        UOPMenuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPMenuMenuMouseClicked(evt);
            }
        });
        jMenu1.add(UOPMenuMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Order");

        UOPPOMenu.setText("Place Order");
        UOPPOMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPPOMenuMouseClicked(evt);
            }
        });
        jMenu2.add(UOPPOMenu);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("About");

        UOPMPMenu.setText("My Profile");
        UOPMPMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPMPMenuMouseClicked(evt);
            }
        });
        jMenu7.add(UOPMPMenu);

        UOPCUMenu.setText("Contact Us");
        UOPCUMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPCUMenuMouseClicked(evt);
            }
        });
        jMenu7.add(UOPCUMenu);

        UOPLogoutMenu.setText("Logout");
        UOPLogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UOPLogoutMenuMouseClicked(evt);
            }
        });
        jMenu7.add(UOPLogoutMenu);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UOPMenuComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UOPMenuComboboxActionPerformed
   
    }//GEN-LAST:event_UOPMenuComboboxActionPerformed

    private void UOPDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UOPDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UOPDeleteButtonActionPerformed

    private void UOPEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UOPEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UOPEditButtonActionPerformed

    private void UOPAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPAddButtonMouseClicked
    String menuName = UOPMenuCombobox.getSelectedItem().toString();
    int quantity = Integer.parseInt(UOPQuantityCombobox.getSelectedItem().toString());
    double price = getPriceForMenu(menuName);
    double total = quantity * price;

    int orderID = orderIDCounter++;
    
    orderTableModel.addRow(new Object[]{orderID, menuName, quantity, price, total});
    
    calculateTotalPrice();
    }//GEN-LAST:event_UOPAddButtonMouseClicked

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked

    }//GEN-LAST:event_OrderTableMouseClicked

    private void UOPEditButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPEditButtonMouseClicked
        int selectedRow = OrderTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row to edit.");
            return;
        }

        String menuName = UOPMenuCombobox.getSelectedItem().toString();
        int quantity = Integer.parseInt(UOPQuantityCombobox.getSelectedItem().toString());
        double price = getPriceForMenu(menuName);
        double total = quantity * price;

        OrderTable.setValueAt(menuName, selectedRow, 1);
        OrderTable.setValueAt(quantity, selectedRow, 2);
        OrderTable.setValueAt(price, selectedRow, 3);
        OrderTable.setValueAt(total, selectedRow, 4);

        JOptionPane.showMessageDialog(null, "Order Updated Successfully!");

    }//GEN-LAST:event_UOPEditButtonMouseClicked

    private void UOPAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UOPAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UOPAddButtonActionPerformed

    private void UOPDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPDeleteButtonMouseClicked
        int selectedRow = OrderTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.");
            return;
        }

        orderTableModel.removeRow(selectedRow);
        JOptionPane.showMessageDialog(null, "Order Deleted Successfully!");
    }//GEN-LAST:event_UOPDeleteButtonMouseClicked

    private void UOPMenuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPMenuMenuMouseClicked
        dispose();
        UserML UMP = new UserML();
        UMP.setLocationRelativeTo(null);
        UMP.setLocationRelativeTo(null);
        UMP.setVisible(true);
    }//GEN-LAST:event_UOPMenuMenuMouseClicked

    private void UOPPOMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPPOMenuMouseClicked
        dispose();
        UserOP UOP = new UserOP();
        UOP.setLocationRelativeTo(null);
        UOP.setLocationRelativeTo(null);
        UOP.setVisible(true);

    }//GEN-LAST:event_UOPPOMenuMouseClicked

    private void UOPMPMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPMPMenuMouseClicked
        dispose();
        UserAP UAP = new UserAP();
        UAP.setLocationRelativeTo(null);
        UAP.setLocationRelativeTo(null);
        UAP.setVisible(true);

    }//GEN-LAST:event_UOPMPMenuMouseClicked

    private void UOPCUMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPCUMenuMouseClicked
        dispose();
        UserCUP UCUP = new UserCUP();
        UCUP.setLocationRelativeTo(null);
        UCUP.setLocationRelativeTo(null);
        UCUP.setVisible(true);
    }//GEN-LAST:event_UOPCUMenuMouseClicked

    private void UOPLogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPLogoutMenuMouseClicked
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_UOPLogoutMenuMouseClicked

    private void UOPNoteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UOPNoteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UOPNoteTFActionPerformed

    private void CashRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashRBActionPerformed

    private void TFRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRBActionPerformed

    private void UOPOrderBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UOPOrderBtnMouseClicked
    String name = OPNameTF.getText();
    String address = OPAddressTF.getText();
    String phoneNumber = OPPhoneTF.getText();
    String note = UOPNoteTF.getText();
    String paymentMethod = CashRB.isSelected() ? "Cash" : "TF"; 

    DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        String menuName = (String) model.getValueAt(i, 1);
        int quantity = (int) model.getValueAt(i, 2);
        double price = (double) model.getValueAt(i, 3);
        double total = (double) model.getValueAt(i, 4);

        try {
            String insertOrderQuery = "INSERT INTO orders (name, address, phone_number, note, payment_method, menu_name, quantity, price, total) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement insertOrderStatement = con.prepareStatement(insertOrderQuery);
            insertOrderStatement.setString(1, name);
            insertOrderStatement.setString(2, address);
            insertOrderStatement.setString(3, phoneNumber);
            insertOrderStatement.setString(4, note);
            insertOrderStatement.setString(5, paymentMethod);
            insertOrderStatement.setString(6, menuName);
            insertOrderStatement.setInt(7, quantity);
            insertOrderStatement.setDouble(8, price);
            insertOrderStatement.setDouble(9, total);
            insertOrderStatement.executeUpdate();
    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error inserting order details: " + ex.getMessage());
        }
    }

    OPNameTF.setText("");
    OPAddressTF.setText("");
    OPPhoneTF.setText("");
    UOPNoteTF.setText("");
    CashRB.setSelected(true);
    UOPMenuCombobox.setSelectedIndex(0);
    UOPQuantityCombobox.setSelectedIndex(0);
    jLabel3.setText((""));
    model.setRowCount(0);

    JOptionPane.showMessageDialog(null, "Order placed successfully!");
    }//GEN-LAST:event_UOPOrderBtnMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserOP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CashRB;
    private javax.swing.JTextField OPAddressTF;
    private javax.swing.JTextField OPNameTF;
    private javax.swing.JTextField OPPhoneTF;
    private javax.swing.JTable OrderTable;
    private javax.swing.JRadioButton TFRB;
    private javax.swing.JButton UOPAddButton;
    private javax.swing.JMenu UOPCUMenu;
    private javax.swing.JButton UOPDeleteButton;
    private javax.swing.JButton UOPEditButton;
    private javax.swing.JMenu UOPLogoutMenu;
    private javax.swing.JMenu UOPMPMenu;
    private javax.swing.JComboBox<String> UOPMenuCombobox;
    private javax.swing.JLabel UOPMenuLabel;
    private javax.swing.JMenu UOPMenuMenu;
    private javax.swing.JTextField UOPNoteTF;
    private javax.swing.JButton UOPOrderBtn;
    private javax.swing.JMenu UOPPOMenu;
    private javax.swing.JComboBox<String> UOPQuantityCombobox;
    private javax.swing.JLabel UOPQuantityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
