/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectSE;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yustina Yunita
 */
public class UserCUP extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public UserCUP() {
        initComponents();
        Config DB = new Config();
        DB.conn();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UCUPNameTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UCUPFeedbackTA = new javax.swing.JTextArea();
        UCUPSendButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UCUPMLMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        UCUPPOMenu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        UCUPMPMenu = new javax.swing.JMenu();
        UCUPCUMenu = new javax.swing.JMenu();
        UCUPLogoutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        jLabel1.setText("Contact Us");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("LunaCafe@gmail.com");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("+62 8123 456 7890");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Store Address");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Lalaland no.333");

        jLabel8.setFont(new java.awt.Font("Goudy Old Style", 3, 36)); // NOI18N
        jLabel8.setText("Feedback form");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Name  ");

        UCUPNameTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Feedback");

        UCUPFeedbackTA.setColumns(20);
        UCUPFeedbackTA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UCUPFeedbackTA.setRows(5);
        jScrollPane1.setViewportView(UCUPFeedbackTA);

        UCUPSendButton.setBackground(new java.awt.Color(255, 204, 204));
        UCUPSendButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UCUPSendButton.setForeground(new java.awt.Color(255, 255, 255));
        UCUPSendButton.setText("Send");
        UCUPSendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCUPSendButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(386, 386, 386))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(UCUPNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UCUPSendButton)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(432, 432, 432))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(UCUPNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(UCUPSendButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        UCUPMLMenu.setText("Menu List");
        UCUPMLMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCUPMLMenuMouseClicked(evt);
            }
        });
        jMenu1.add(UCUPMLMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Order");

        UCUPPOMenu.setText("Place Order");
        UCUPPOMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCUPPOMenuMouseClicked(evt);
            }
        });
        jMenu2.add(UCUPPOMenu);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("About");

        UCUPMPMenu.setText("My Profile");
        UCUPMPMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCUPMPMenuMouseClicked(evt);
            }
        });
        jMenu6.add(UCUPMPMenu);

        UCUPCUMenu.setText("Contact Us");
        UCUPCUMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCUPCUMenuMouseClicked(evt);
            }
        });
        jMenu6.add(UCUPCUMenu);

        UCUPLogoutMenu.setText("Logout");
        UCUPLogoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UCUPLogoutMenuMouseClicked(evt);
            }
        });
        jMenu6.add(UCUPLogoutMenu);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void UCUPMLMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCUPMLMenuMouseClicked
        dispose();
        UserML UMP = new UserML();
        UMP.setLocationRelativeTo(null);
        UMP.setLocationRelativeTo(null);
        UMP.setVisible(true);
    }//GEN-LAST:event_UCUPMLMenuMouseClicked

    private void UCUPPOMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCUPPOMenuMouseClicked
        dispose();
        UserOP UOP = new UserOP();
        UOP.setLocationRelativeTo(null);
        UOP.setLocationRelativeTo(null);
        UOP.setVisible(true);
    }//GEN-LAST:event_UCUPPOMenuMouseClicked

    private void UCUPMPMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCUPMPMenuMouseClicked
        dispose();
        UserAP UAP = new UserAP();
        UAP.setLocationRelativeTo(null);
        UAP.setLocationRelativeTo(null);
        UAP.setVisible(true);
    }//GEN-LAST:event_UCUPMPMenuMouseClicked

    private void UCUPCUMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCUPCUMenuMouseClicked
        dispose();
        UserCUP UCUP = new UserCUP();
        UCUP.setLocationRelativeTo(null);
        UCUP.setLocationRelativeTo(null);
        UCUP.setVisible(true);
    }//GEN-LAST:event_UCUPCUMenuMouseClicked

    private void UCUPLogoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCUPLogoutMenuMouseClicked
        dispose();
        MainPage MP = new MainPage();
        MP.setLocationRelativeTo(null);
        MP.setLocationRelativeTo(null);
        MP.setVisible(true);
    }//GEN-LAST:event_UCUPLogoutMenuMouseClicked

    private void UCUPSendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UCUPSendButtonMouseClicked
        String name = UCUPNameTF.getText();
        String feedback = UCUPFeedbackTA.getText();
        
        try {
           String insertQuery = "INSERT INTO feedback (name, feedback) VALUES ('" + name + "', '" + feedback + "')";
            int result = stat.executeUpdate(insertQuery);
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "Send! Thank you for your feedback!!");
                UCUPNameTF.setText("");
                UCUPFeedbackTA.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Sending Error!! Please Try Again.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sending Error!! Please Try Again.");
        }
    }//GEN-LAST:event_UCUPSendButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu UCUPCUMenu;
    private javax.swing.JTextArea UCUPFeedbackTA;
    private javax.swing.JMenu UCUPLogoutMenu;
    private javax.swing.JMenu UCUPMLMenu;
    private javax.swing.JMenu UCUPMPMenu;
    private javax.swing.JTextField UCUPNameTF;
    private javax.swing.JMenu UCUPPOMenu;
    private javax.swing.JButton UCUPSendButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
